### ISSUE TITLE
Firefox adaptation

### ISSUE THREAD

**Issue by Defraedd** [rudiedirkx/FontBlocker#21]
This is not an issue, but rather a request. Would it be easy to adapt this extension to be compatible with Firefox ? I tried to import it thanks to the Firefox extension "Chrome Store Foxified", but it doesn't work.
Thank you.

**Comment by rudiedirkx** [comment]
Might be. It's all pretty simple: a synced database (could be local) and domain-based CSS injection.

But I've no idea how Firefox extensions work these days.

**Comment by Defraedd** [comment]
Thanks. I heard there was a new unified framework to develop extensions, called WebExtensions, https://developer.mozilla.org/en-US/Add-ons/WebExtensions/What_are_WebExtensions 
I wasn't sure if you did this one using this new approach or not... 
Maybe I'll take a look if I have time. But I've never developed add-ons before, so it might take time.

**Comment by rudiedirkx** [comment]
That's cool! I didn't know Firefox supported Chrome extensions (or they use the same framework, whichever).

I've tried some:
1. Literally: Firefox can't find `chrome.storage.sync`, so I changed it to `chrome.storage.local`
2. Something else doesn't work, but I can't find what...

The latest commit has the `sync` vs `local` option. Goodluck =)

**Comment by Defraedd** [comment]
Thanks for your encouragements. 
I found a stubborn site, that still loads the web font ("Raleway") even though I block it. https://www.raymond.cc/blog/   But on the home page it works, it's on each article that the page loads, blocks the font, and then after a fraction of a second, the annoying webfont replaces my normal Arial default font! I don't know if there is anything to do to prevent this...   On Firefox, when I use the extension "Toggle Document Fonts" on that page, it is blocked indeed. (but the problem with this extension is that it will block all webfonts, even the ones I want to keep, like those icon bearing fonts, we can't pick & choose the font we want to block, like with your add-on).

**Comment by rudiedirkx** [comment]
You're talking about Chrome, right? That should be another issue. This one is only about a Firefox adaptation.

**Comment by Defraedd** [comment]
Yes I was talking about Chrome in my last remark (problem with one site). Sorry I'm quite new to Github. Is it worth it that I create a new issue for that ?

**Comment by rudiedirkx** [comment]
If you want me to look at it, yes please.

Every time I get a notification about this issue, I'm hoping you did it. Where is it? Did you do it? Where's the Firefox extension?? =)

**Comment by rudiedirkx** [comment]
Version 1.17 should work in Firefox, but I'm not adding it to their store, because the process sucks.
