### ISSUE TITLE
Not working on idnes.cz

### ISSUE THREAD

**Issue by redfoxcz** [rudiedirkx/FontBlocker#24]
There are some web compatibility issues now... for example, it does not work with the site fotbal.idnes.cz or sport.idnes.cz now - but it worked before.

EDIT: I just found out that it is caused by collision of Adblock Plus filters rules (Easylist) with this extension.

**Comment by rudiedirkx** [comment]
Which fonts are you trying to block?

I wouldn't know how AdBlock would interfere...
