### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Janmm14** [rudiedirkx/FontBlocker#26]
Blocked fonts still show on the fingerprint data one can see at https://panopticlick.eff.org/

It would be great to be able to block certain fonts everywhere.

Using devtools to edit font-family doesn't prevent the font from appearing.

**Comment by rudiedirkx** [comment]
What do you mean "on the fingerprint data"? Did you block a font and nothing happened? What did you try to block? What name did the confirmation popup say?

You can block certain fonts everywhere. Go to the options page and click on the arrow next to the website/domain.

**Comment by Janmm14** [comment]
if doing the test a globally blocked font is still detected and shown in the fingerprint details under "System Fonts" (page is not visisble in the lbocked font, but the blocked font is listed)

blocking fonts now seems to work, i restarted the browser after installation.

and ignore the part with devtools

**Comment by rudiedirkx** [comment]
It's not perfect, I know. Some characters or subsets are still loaded from the original font, and italic and bold are unreliable. But mostly it works, right!

Wherever it definitely doesn't work, give me a good test case (which public website, which font at which location, screenshots of before & after, etc), and I'll try to find why it doesn't work.
