### ISSUE TITLE
Chrome console reports "Unchecked runtime.lastError: The message port closed before a response was received."

### ISSUE THREAD

**Issue by manthey** [rudiedirkx/FontBlocker#27]
Calls to `browser.runtime.onMessage.addListener` are expected to return a Promise.  If they don't the console logs `Unchecked runtime.lastError: The message port closed before a response was received.`.  I don't think it causes any harm, but it would be nice to not emit console errors.

**Comment by rudiedirkx** [comment]
Message port in Chrome is always buggy. Fontblocker doesn't even use it. I won't handle an error triggered by another program. The error will go away soon, with the next browsers restart or update.

**Comment by rudiedirkx** [comment]
Unnecesarily buggy. Will fix.
