### ISSUE TITLE
FontBlocker Options dont work

### ISSUE THREAD

**Issue by username7291** [rudiedirkx/FontBlocker#28]
The Options page open "Loading" "Font name 	Website Blocked on" "Export" "Import" "Import"
All empty, clicking on it doesnt do anyting.

Can Fontblocker block any webfont,  exept 1 one 1 Website?
If yes can i set this by edit a file without using the broken "FontBlocker Options"?
Firefox is unable todo Antialiasing on Window 7 with System AA Disabled(On XP this work),
cause all webfonts look ugly. But on the Weather site i need only 1/2 Webfonts with symbol. 
Right now i use Silentblock, but its annoying to add every Website.

Firefox 52.9 ESR/Win 7/tryed disabling other Addons/tryed different Versions.

**Comment by rudiedirkx** [comment]
There are a few fake Firefox font blockers. Which one do you have? URL of addon page?

> Can Fontblocker block any webfont, exept 1 one 1 Website?

No. Default is allow. Add fonts to block.

I know nothing about anti aliasing. I think Firefox has a native option to block ALL webfonts, but no option to allow some.

**Comment by rudiedirkx** [comment]
Options page works for me in Firefox 67 on Win 7.

Test page: https://webblocks.nl/tests/fonts.html

Options page:

![image](https://user-images.githubusercontent.com/168024/58573370-dafadb80-823d-11e9-9ccf-944dac487e2c.png)

**Comment by username7291** [comment]
Anti aliasing is smothing, it makes fonts unsharp/blurry. Looks like you require glasses on windows.
But webfonts are calculated or something they looks ugly without Anti aliasing https://i.stack.imgur.com/zyhdD.png

I know this option to block all, but on my weather site weather symbols are missing if i disable all.
https://addons.mozilla.org/de/firefox/addon/font-blocker-foxified/versions/
and https://addons.mozilla.org/de/firefox/addon/font-blocker/ both dont work.

No there are no Fonts in the options page, but the plugins can block single fonts on single sites with context menu entry.
Maybe you use something that only works with higher Firefox versions? Or you installed files by hand?
I doesnt find the files that are included on the options page on my Harddisk.
I cant use higher FF Versions cause very imported Plugins doesnt work, looks ugly, and it runs out of memory on 4GB Computer easy.
Maybe if you like to fix this, you could add global block with allow entrys?

**Comment by rudiedirkx** [comment]
> I doesnt find the files that are included on the options page on my Harddisk.

Which files? The fallback (Arial etc)? So are there fonts on the Options page, or not..?

Firefox 67 works. I can't fix what isn't broken (for me).

I won't add a global block with specific allow entries. Maybe other extensions already do this? Sounds sensible.

**Comment by username7291** [comment]
Files that are part of the Plugin, the options page link to some css/javascript files.
No there are no fonts, no cycle gadget, no dates, no "x".
Another plugin for this doesnt exits. But its okay, i found a ttf font link in the Weather side, installed it and disable webfonts with gfx.downloadable_fonts.enabled;false. The site use now the the offline symbol font well.
