### ISSUE TITLE
Block System Fonts?

### ISSUE THREAD

**Issue by chris-dura** [rudiedirkx/FontBlocker#29]
Is there any way to block a system font?

My situation is my company has a custom font, and I need to test out that the CSS is configured properly. BUT, I also need the font installed locally because I constantly need to open desktop apps like Photoshop, Keynote, Adobe XD with designs that utilize our font.

Constantly disabling/enabling the locally installed version in Fontbook every time I switch is just a royal PITA.

I'm pretty sure devtools notes whether the font was loaded from the "network" or is a "system" font? Perhaps there's a way to adjust this extension to only block the local version of a particular font?

**Comment by rudiedirkx** [comment]
Fontblocker doesn't know anything about the loaded font. It doesn't even know which font is loaded/displayed. It just takes the first font name and overwrites its definition. It's way dumber than you'd expect, and it's kind of a miracle that it even works. And sometimes it doesn't and I've no idea why.

So to most questions: no, or I don't know, and I don't know why! =(

If you know a better way to detect font stuff (like Devtools can), I'd love to hear it. I think extensions don't have access to any Devtools magic.

**Comment by chris-dura** [comment]
bummer.

I'll probably never have time to dig in, but extensions can _extend_ DevTools... but I don't know if that is a way to get whether a font was loaded from the system or not (perhaps via the network requests):
https://developer.chrome.com/extensions/devtools

And, there is an open feature request in Chromium to enable this exact thing:
https://bugs.chromium.org/p/chromium/issues/detail?id=472136

**Comment by rudiedirkx** [comment]
Extending Devtools only helps within Devtools. A Devtools extension doesn't have website power if Devtools isn't open. That's not good enough.

Isn't the chromium issue the the exact opposite of what fontblocker does?: "Only Use Web Fonts". Fontblocker exists to block (annoying) webfonts.

**Comment by chris-dura** [comment]
Well, obviously developers are asking for this feature while they're developing, so DevTools being open is probably good enough for the users asking for it 🤷‍♀ 

I don't think it's a stretch to say "blocking system fonts" just seemed to be related functionality (and there's actual people asking for it) 🤷‍♀

But, sure, if "Font Blocker" only ever exists as an "(Annoying) Web Font Blocker", so be it.

**Comment by rudiedirkx** [comment]
Fontblocker was and is meant as a simple tool to block any font. When you visit the website a week later, the font is still blocked. Not any Devtools necessary. It has to be super simple, not for developers. Developers have many methods/tools to block fonts.

If you know a better way to block fonts with Devtools, I'd love to see it.

I can't see any point in blocking all system fonts and only loading webfonts... That's weird... You like the white screen, the font flash, the JS loaders? Maybe that's just grumpy me grumping on webfonts, the scourge of the web.

**Comment by chris-dura** [comment]
> Developers have many methods/tools to block fonts.

Yes, but they have none (afaict) to block system fonts (so that they may _test_ their web fonts).

> I can't see any point in blocking all system fonts and only loading webfonts... That's weird... You like the white screen, the font flash, the JS loaders?

The reasons were in [that Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=472136#c20) I sent, but to sum it up.

- It is common that developers/designers install custom fonts on their local systems. It's the only way to use the fonts with desktop apps, like Photoshop, PowerPoint, Word, etc.
- If a browser finds a font on the developer/designer's machine named "My Custom Font", it will load that _system_ font, _instead_ of the _web_ font.
- This does not emulate what actual users of a website would experience, because other users will _not_ have the font installed locally on their system.
- So, developers/designers have to constantly _disable/uninstall_ the local font when they want to test that the _web_ font on their website is working properly.
- And, then they have to _re-enable/re-install_ the local font every time they want to use it in a desktop app.
- This is annoying and slow and just generally inefficient.

**Comment by rudiedirkx** [comment]
Ooooh. Yeah, Fontblocker doesn't do that. It's not nearly reliable enough to be able to do that. That maybe could be a Devtools extension, maybe, because it has more fine grained font control, but maybe not even enough.
