### ISSUE TITLE
Not blocking bolded versions of blocked fonts

### ISSUE THREAD

**Issue by stareyedwonder** [rudiedirkx/FontBlocker#30]
Hi! I'm using Firefox. Thanks for putting this add-on together! I've blocked a font on a page, and it seems to be working for most of the font, but it seems to be "skipping" bolded representations of the font. Am I missing something? Thanks!

**Comment by rudiedirkx** [comment]
You're not missing anything. That's how limited it works these days. It depends on how the custom font was loaded with `@font-face`. Fontblocker only overrides the 'normal' variant: https://github.com/rudiedirkx/fontblocker/blob/master/fontblocker.content.js#L43 not the bold or italic variants. It used to, but it always worked poorly, and then not at all.

The world needs a better way to block/cancel specific fonts, but I don't know how.

**Comment by stareyedwonder** [comment]
OK; thanks for the comments.

_____________________________________________________________________________________
Christian Schroeder
