### ISSUE TITLE
Works only sometimes

### ISSUE THREAD

**Issue by username7291** [rudiedirkx/FontBlocker#32]
Cause newer Firefox PDF viewer is broken i have to enable webfonts, but i want it only for pdf.
Cause almost any webfonts looks ugly without Antialiasing i dont want them(with Antialiasing whole Computer looks unsharp like i require glasses).
The Menu most times dont open the requester to block(even if you try it 3 times).
Second thing is on one page are often many webfonts, cant you make this on a whitelist base?

**Comment by rudiedirkx** [comment]
> The Menu most times dont open the requester to block(even if you try it 3 times).

Yes, it's not very foolproof. I can't fix that.

> Second thing is on one page are often many webfonts, cant you make this on a whitelist base?

No, that's not how this blocking works. It has to (very) explicitly block exact font names.
